name: ci
on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        if: github.event_name == 'push'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Set Cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build
        working-directory: Documentation-Site  

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        run: mkdocs gh-deploy --force
        working-directory: Documentation-Site  